### ISSUE TITLE
Crash if user enters an invalid port number for a server

### ISSUE THREAD

**Issue by justdave** [justdave/MCStatus#10]
```
java.lang.IllegalArgumentException: Port out of range: 265571
	at java.net.Socket.checkDestination(Socket.java:306)
	at java.net.Socket.tryAllAddresses(Socket.java:129)
	at java.net.Socket.<init>(Socket.java:180)
	at java.net.Socket.<init>(Socket.java:152)
	at net.justdave.mcstatus.MinecraftServer.query(MinecraftServer.java:256)
	at net.justdave.mcstatus.MainActivity$2.run(MainActivity.java:231)
	at java.lang.Thread.run(Thread.java:818)
```

This is obviously a user error, but I should trap for it and tell them nicely instead of crashing.

**Comment by justdave** [comment]
ok, I just reproduced this, and it's worse than it sounds - need to fix this asap :-)

Once you've entered a server with an invalid port number, it crashes on launch from then on, and there's no way to fix the problem.
